config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'hello#index'

  get 'diaries/condition' => 'diaries#condition_index'
  
  resources :diaries
 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord

    belongs_to :user
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :diaries, dependent: :destroy

         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController

    before_action :authenticate_user!


    def index
        @user_diaries = Diary.where(user_id: current_user.id).order(diary_date: "ASC")
        @days = ["日曜日", "月曜日", "火曜日", "水曜日", "木曜日", "金曜日", "土曜日"]

        @search = params[:search]
        if @search.present?
        @user_diaries = @user_diaries.where("body LIKE ?", "%#{@search}%")
            .or(@user_diaries.where(diary_date: "%#{@search}%"))
            .or(@user_diaries.where("mental_comment LIKE ?", "%#{@search}%"))
            .or(@user_diaries.where("physical_comment LIKE ?", "%#{@search}%"))
        end
    end

    def new
        @diary = Diary.new
    end
    
    def create
        diary = Diary.new(diary_params)
        diary.user_id = current_user.id

        if diary.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
    end

    def show
        @diary = Diary.find(params[:id])
        @days = ["日曜日", "月曜日", "火曜日", "水曜日", "木曜日", "金曜日", "土曜日"]
    end

    def edit
        @diary = Diary.find(params[:id])
    end
    
    def update
        diary = Diary.find(params[:id])

        if diary.update(diary_params)
            redirect_to :action => "index"
        else
            redirect_to :action => "edit"
        end
    end

    def destroy
        diary = Diary.find(params[:id])
        diary.destroy
        redirect_to action: :index
    end

    def condition_index
        @user_diaries = Diary.where(user_id: current_user.id).order(diary_date: "ASC")
        @days = ["日曜日", "月曜日", "火曜日", "水曜日", "木曜日", "金曜日", "土曜日"]

        # グラフ用のデータを作る

        lasts = @user_diaries.last(8)
        mental_data = Array.new
        physical_data = Array.new

        lasts.each do |last|
            mental_array = Array.new
            physical_array = Array.new
            mental_array.push last.diary_date.strftime('%m/%d')
            physical_array.push last.diary_date.strftime('%m/%d')
        
            m = last.mental_condition
            if m == "良い"
                mental_array.push 2
            elsif m == "少し悪い"
                mental_array.push 1
            else
                mental_array.push 0
            end

            p = last.physical_condition
            if p == "良い"
                physical_array.push 2
            elsif p == "少し悪い"
                physical_array.push 1
            else
                physical_array.push 0
            end

            mental_data.push mental_array
            physical_data.push physical_array
            
        end

        @chart_data = [{name: "心の状態", data: mental_data}, {name: "体の状態", data: physical_data}]

    
        
    end


    private
    def diary_params
        params.require(:diary).permit(:body, :mental_condition, :mental_comment, :physical_condition, :physical_comment, :diary_date)
    end

end

app/controllers/hello_controller.rb
class HelloController < ApplicationController

    def index
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/views/diaries/condition_index.html.erb
<%= stylesheet_link_tag 'condition_index', :media => "all" %>

<div class="semi-header">
  <h2>健康状態</h2>
</div>

<div class="space">
</div>

<div class="charts">
    <div class="scale">
        <div>良い</div>
        <div>少し悪い</div>
        <div>悪い</div>
    </div>
    <div class="chart">
        <%= line_chart @chart_data, curve: false, colors: ["#BF0426", "#034AA6"] %>
    </div>
</div>

<div class="diaries-container">
    <% @user_diaries.reverse_each do |d| %>
        <div class="diary">
            <div class="first-brock">
                <ul class="date_days">
                    <li><%= d.diary_date.strftime('%m月%d日') %></li>
                    <li><%= @days[d.diary_date.wday] %></li>
                </ul>
                <ul class="links">
                    <li><%= link_to "編集する", edit_diary_path(d.id), method: :get %></li>
                    <li><%= link_to "詳細", diary_path(d.id), method: :get %></li>
                </ul>
            </div>
            <div class="third-brock">
                <div class="up">
                    <ul>
                        <li><span class="li_title">心の状態</span></li>
                        <li><%= d.mental_condition %></li>
                    </ul>
                </div>
                <div class="down">
                    <ul class="down">
                        <li><span class="comment"><%= d.mental_comment %></span></li>
                    </ul>
                </div>
            </div>
            <div class="forth-brock">
                <div class="up">
                    <ul>
                        <li><span class="li_title">体の状態</span></li>
                        <li><%= d.physical_condition %></li>
                    </ul>
                </div>
                <div class="down">
                    <ul>
                        <li><span class="comment"><%= d.physical_comment %></span></li>
                    </ul>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/diaries/edit.html.erb
<%= stylesheet_link_tag 'edit', :media => "all" %>

<div class="semi-header">
  <h2>日記を編集</h2>
</div>


<div class="post-background">
    <div class="post-container">
    <%= form_for @diary do |f| %>

        <div class="field">
        <%= f.label :diary_date, "日付" %>
        <%= raw sprintf(
                f.date_select(
                    :diary_date,{
                    use_month_numbers: true,
                    date_separator: '%s'},
                    class:"date-select"),
                '年 ', '月 ') + '日' %>
        </div>

        <div class="field">
        <%= f.label :body, "本文" %>
        <br>
        <%= f.text_area :body, :size=>"100x8" %>
        </div>

        <div class="field">
        <%= f.label :mental_condition, "心の状態" %>
        <%= f.radio_button :mental_condition, "良い", checked: true %>良い
        <%= f.radio_button :mental_condition, "少し悪い" %>少し悪い
        <%= f.radio_button :mental_condition, "悪い" %>悪い
        </div>

        <div class="field">
        <%= f.label :mental_comment, "コメント" %>
        <%= f.text_field :mental_comment, :size => 140 %>
        </div>

        <div class="field">
        <%= f.label :physical_condition, "体の状態" %>
        <%= f.radio_button :physical_condition, "良い", checked: true %>良い
        <%= f.radio_button :physical_condition, "少し悪い" %>少し悪い
        <%= f.radio_button :physical_condition, "悪い" %>悪い
        </div>

        <div class="field">
        <%= f.label :physical_comment, "コメント" %>
        <%= f.text_field :physical_comment, :size => 140 %>
        </div>
        
        <%= f.submit "保存する" %>
    <% end %>
    </div>
</div>

app/views/diaries/index.html.erb
<%= stylesheet_link_tag 'index', :media => "all" %>

<div class="semi-header">

    <h2>日記一覧</h2>

    <div class="search-box">
        
        <%= form_tag({controller: "diaries", action: "index"}, method: :get) do %>
            <span><%= text_field_tag :search, @search %></span>
            <span><%= submit_tag '検索'  %></span>
        <% end %>
            <span><%= button_to "検索リセット", diaries_path, method: :get %></span>
            <span>日付を検索する場合 (例) 2022-11-15</span>
    </div>

</div>

<div class="diaries-container">

    <% @user_diaries.reverse_each do |d| %>
        <div class="diary">
            <div class="first-brock">
                <ul class="date_days">
                    <li><%= d.diary_date.strftime('%Y年%m月%d日') %></li>
                    <li><%= @days[d.diary_date.wday] %></li>
                </ul>
                <ul class="links">
                    <li><%= link_to "編集する", edit_diary_path(d.id), method: :get %></li>
                    <li><%= link_to "詳細", diary_path(d.id), method: :get %></li>
                </ul>
            </div>
            <div class="second-brock">
                <%= d.body %>
            </div>
            <div class="third-brock">
                <ul>
                    <li><span class="li_title">心の状態</span></li>
                    <li><%= d.mental_condition %></li>
                    <li><span class="comment"><%= d.mental_comment %></span></li>
                </ul>
            </div>
            <div class="forth-brock">
                <ul>
                    <li><span class="li_title">体の状態</span></li>
                    <li><%= d.physical_condition %></li>
                    <li><span class="comment"><%= d.physical_comment %></span></li>
                </ul>
            </div>
        </div>
    
    <% end %>

</div>

app/views/diaries/new.html.erb
<%= stylesheet_link_tag 'new', :media => "all" %>


  <div class="semi-header">
    <h2>日記を書く</h2>
  </div>

<div class="post-background">
  <div class="post-container">
    <%= form_for @diary do |f| %>

      <div class="field">
        <%= f.label :diary_date, "日付" %>
        <%= raw sprintf(
                f.date_select(
                  :diary_date,{
                  use_month_numbers: true,
                  date_separator: '%s'},
                  class:"date-select"),
                '年 ', '月 ') + '日' %>
      </div>

      <div class="field">
        <%= f.label :body, "本文" %>
        <br>
        <%= f.text_area :body, :size=>"100x8" %>
      </div>

      <div class="field">
        <%= f.label :mental_condition, "心の状態" %>
        <%= f.radio_button :mental_condition, "良い", checked: true %>良い
        <%= f.radio_button :mental_condition, "少し悪い" %>少し悪い
        <%= f.radio_button :mental_condition, "悪い" %>悪い
      </div>

      <div class="field">
        <%= f.label :mental_comment, "コメント" %>
        <%= f.text_field :mental_comment, :size => 140 %>
      </div>

      <div class="field">
        <%= f.label :physical_condition, "体の状態" %>
        <%= f.radio_button :physical_condition, "良い", checked: true %>良い
        <%= f.radio_button :physical_condition, "少し悪い" %>少し悪い
        <%= f.radio_button :physical_condition, "悪い" %>悪い
      </div>

      <div class="field">
        <%= f.label :physical_comment, "コメント" %>
        <%= f.text_field :physical_comment, :size => 140 %>
      </div>
      
      <%= f.submit "保存する" %>
    <% end %>
  </div>
</div>

app/views/diaries/show.html.erb
<%= stylesheet_link_tag 'show', :media => "all" %>

<div class="semi-header">
  <h2>日記詳細</h2>
</div>


<div class="diary-background">
    <div class="diary">
        <div class="first-brock">
            <ul class="date_days">
                <li><%= @diary.diary_date.strftime('%Y年%m月%d日') %></li>
                <li><%= @days[@diary.diary_date.wday] %></li>
            </ul>
        </div>
        <div class="second-brock">
            <%= @diary.body %>
        </div>
        <div class="third-brock">
            <ul>
                <li><span class="li_title">心の状態</span></li>
                <li><%= @diary.mental_condition %></li>
                <li><span class="comment"><%= @diary.mental_comment %></span></li>
            </ul>
        </div>
        <div class="forth-brock">
            <ul>
                <li><span class="li_title">体の状態</span></li>
                <li><%= @diary.physical_condition %></li>
                <li><span class="comment"><%= @diary.physical_comment %></span></li>
            </ul>
        </div>
    </div>

    <div class="delete">
        <%= button_to "削除する", diary_path(@diary.id), method: :delete, class: "button" %>
    </div>
</div>

app/views/hello/index.html.erb
<%= stylesheet_link_tag 'hello_index', :media => "all" %>

<div class="semi-header">
  <h2>Home</h2>
</div>

<div class="background">

    <p class="app_name"><span class="t">Diary </span><span class="s">with Health</span></p>
    <p class="app_explanation">日記をつけながら、<br>心と体の健康を管理する<br>アプリ</p>
    
    <div class="contents">
        <ul>
            <li><%= link_to "ログイン", diaries_path %></li>
            <li><div class="sample">サンプルはこちら↑</div></li>
        </ul>

        <ul>
            <li><%= link_to "新規登録", new_user_registration_path %></li>
        </ul>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary with Health</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <h1><span class="t">Diary </span><span class="s">with Health</span></h1>
      <div class="header-list">
      <ul>
        <li><%= link_to "日記を書く",new_diary_path %></li>
        <li><%= link_to "日記一覧", diaries_path %></li>
        <li><%= link_to "健康状態",diaries_condition_path %></li>
        <li><%= link_to "ログアウト",destroy_user_session_path, method: :delete %></li>
      </ul>
      </div>
    </header>

    <main>
      <%= yield %>
    </main>

<% if false %>
    # <footer>
    #   <p>Copyright © GeekSalon All Rights Reserved.</p>
    # </footer>
<% end %>

  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<div class="renderlink_signup">
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end %>
</div>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れた方はこちら", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>